### ISSUE TITLE
Example screenshots of the buttons

### ISSUE THREAD

**Issue by jayroh** [mariosant/better-bourbon-buttons#2]
For a piece of sass/bourbon work saying that it's better than the default - the best way to convey that would be to show (in addition to tell).

Therefore, screenshots would be pretty great :)

**Comment by mariosant** [comment]
Thanks for your interest @jayroh! This project didn't have the required energy to make it real though. I had created a simple demo website which you can visit, at http://mariosant.github.io/bbb-website in case you are interested.

**Comment by jayroh** [comment]
PR #3 submitted with a link to your site :)

**Comment by mariosant** [comment]
Merged! Thank you very much @jayroh!
